### ISSUE TITLE
Abnormal Display of Description

### ISSUE THREAD

**Issue by songyuc** [KimythAnly/qqdm#1]
Hi, guys,
I tried this, but display of the demo seems not good on PyCharm as,
![image](https://user-images.githubusercontent.com/27288110/172557341-e40e6ae2-16f0-4bc2-be8c-960e5fa1c6a0.png)
So, how to solve this?

Your answer and guide will be appreciated!

**Comment by KimythAnly** [comment]
https://stackoverflow.com/questions/45012964/stdout-progress-bars-dont-work-in-pycharm
Not sure if this helps.
